name: Python Flask CI/CD

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Change this to your Python version if different

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add commands to run your tests here
        pytest

    - name: Build HTML/CSS assets
      run: |
        # If you have any build steps for your HTML/CSS (e.g., minification, compilation), add them here

    - name: Run Flask app
      run: |
        flask run --host=0.0.0.0 --port=5000  # Adjust the host and port as needed

    # You can add additional steps for deployment, caching, notifications, etc. as needed.
